title: Habezai's site

description: Habezai的个人网站

theme: just-the-docs

url: https://habezai.github.io/

aux_links:
  本项目的Repository: https://github.com/habezai/home

# logo: "/assets/images/PQC.png"
